### ISSUE TITLE
shot-consumer-compose fails on emulator

### ISSUE THREAD

**Issue by MyDogTom** [pedrovgs/Shot#243]
`app:executeScreenshotTests -Precord` fails on emulator with `java.io.IOException: No such file or directory`. I tried API 29 and API26. On real device this command succeed. 

MacOS: Big Sur 11.4

Am I missing something? 

### Expected behaviour
Should record screenshots.

### Actual behaviour
Each test fails with

```
java.io.IOException: No such file or directory
at java.io.UnixFileSystem.createFileExclusively0(Native Method)
at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
at java.io.File.createNewFile(File.java:1008)
at com.karumi.shot.compose.ScreenshotSaver.createFileIfNotExists(ScreenshotSaver.kt:77)
at com.karumi.shot.compose.ScreenshotSaver.saveScreenshotBitmap(ScreenshotSaver.kt:59)
at com.karumi.shot.compose.ScreenshotSaver.saveScreenshot(ScreenshotSaver.kt:21)
at com.karumi.shot.compose.ComposeScreenshot.saveScreenshot(ComposeScreenshot.kt:22)
at com.karumi.shot.ScreenshotTest$DefaultImpls.compareScreenshot(ScreenshotTest.kt:144)
at com.karumi.shotconsumercompose.GreetingScreenshotTest.compareScreenshot(GreetingScreenshotTest.kt:15)
at com.karumi.shot.ScreenshotTest$DefaultImpls.compareScreenshot(ScreenshotTest.kt:116)
at com.karumi.shotconsumercompose.GreetingScreenshotTest.compareScreenshot(GreetingScreenshotTest.kt:15)
at com.karumi.shot.ScreenshotTest$DefaultImpls.compareScreenshot$default(ScreenshotTest.kt:114)
at com.karumi.shotconsumercompose.GreetingScreenshotTest.rendersAGreetingWithALongText(GreetingScreenshotTest.kt:47)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
at androidx.compose.ui.test.junit4.AndroidComposeTestRule$AndroidComposeStatement.evaluateInner(AndroidComposeTestRule.android.kt:361)
at androidx.compose.ui.test.junit4.AndroidComposeTestRule$AndroidComposeStatement.evaluate(AndroidComposeTestRule.android.kt:350)
at androidx.compose.ui.test.junit4.android.EspressoLink$getStatementFor$1.evaluate(EspressoLink.android.kt:63)
at androidx.compose.ui.test.junit4.IdlingResourceRegistry$getStatementFor$1.evaluate(IdlingResourceRegistry.jvm.kt:160)
at androidx.compose.ui.test.junit4.android.ComposeRootRegistry$getStatementFor$1.evaluate(ComposeRootRegistry.android.kt:150)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
```

### Steps to reproduce
execute `./gradlew app:executeScreenshotTests -Precord` while using emulator.

### Version of the library
Current master. Uses Shot version 5.11.0.

**Comment by MyDogTom** [comment]
In order to overcome this issue I had to add `android:requestLegacyExternalStorage="true"`. It's a bit confusing because readme says it's not needed anymore

>Since Shot 5.8.0 we provide support for devices running API >= 29. There is no need to configure android:requestLegacyExternalStorage="true" or provide any special storage permission in your test `AndroidManifest`.

https://github.com/Karumi/Shot#using-shot-on-api-29

**Comment by pedrovgs** [comment]
Hey @MyDogTom I'm checking and the consumer sample project you mention is working on CI and also on my laptop without the flag you mention. Could you give us more information about how to reproduce this issue? I think I'm missing something because the project is working fine on GitHub actions CI.

**Comment by AlexandreCrettet** [comment]
I have the same problem. Adding `android:requestLegacyExternalStorage="true"` or changing the API version (from 23 to 32) does not help.
@pedrovgs Didn't you do anything else to solve this issue? Maybe it comes from the configuration of the emulator, but I can't find anything related.

**Comment by MyDogTom** [comment]
I close the issue as I won't be able to dig deeper. Sorry.
In case someone else encounters the same problem, feel free to reopen and please provide more details. See my previous comment for the workaround.

**Comment by PierreCapo** [comment]
I had the same error with an API28 emulator, even if I tried with the aforementioned `android:requestLegacyExternalStorage` fix it didn't work. Running the tests API30 emulator fixed the problem.

**Comment by MakarenkoVlad** [comment]
same as for @PierreCapo
