### ISSUE TITLE
ExecuteScreenshotTests -Precord fail when ran for the first time

### ISSUE THREAD

**Issue by gmarques33** [pedrovgs/Shot#267]
### Actual behaviour

If I clone the repo, delete the `shot-consumer-compose/screenshots` folder and run `./gradlew executeScreenshotTests -Precord` on `shot-consumer-compose`
I get: 
``` 
> Task :app:connectedProDebugAndroidTest
Starting 10 tests on Pixel 2 XL - 11

> Task :app:proDebugDownloadScreenshots
⬇️  Pulling screenshots from your connected devices!

> Task :app:proDebugExecuteScreenshotTests FAILED
💾  Saving screenshots.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:proDebugExecuteScreenshotTests'.
> java.nio.file.NoSuchFileException: /Users/gmarques/test/Shot/shot-consumer-compose/app/screenshots/pro/debug/com.karumi.shotconsumercompose.GreetingScreenshotTest_rendersAGreetingWithAnEmptyText.png

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
```

The tests run normally, the screenshots are taken and copied to the computer, but they're being saved on:
```
/Users/gmarques/test/Shot/shot-consumer-compose/app/screenshots/pro/debug/screenshots-default
```

and I get this error that the screenshots aren't available on:
```
/Users/gmarques/test/Shot/shot-consumer-compose/app/screenshots/pro/debug/
```

If I manually copy the content from `/debug/screenshots-default` to '/debug' the test will run normally and subsequent executions with `-Precord` will update the screenshots.

The only problem is when I still don't have the screenshot folder populated and have to run with `-Precord`

### Expected behaviour

`./gradlew executeScreenshotTests -Precord` to run successfully even when there's no screenshots folder.

### Steps to reproduce
* Clone repo.
* Delete `shot-consumer-compose/screenshots` folder.
* Run ./gradlew executeScreenshotTests -Precord` on `shot-consumer-compose`.

I had the same behaviour on my project and on the sample project.

### Version of the library
Shot 5.12.0
Mac OS 11.6.1
adoptopenjdk-11
Pixel 2 XL with Android 11

**Comment by gmarques33** [comment]
This PR: https://github.com/pedrovgs/Shot/pull/259 seems to have caused the issue. Version 5.11.2 works as expected.

**Comment by gmarques33** [comment]
Stacktrace:

```
Caused by: java.nio.file.NoSuchFileException: /Users/gmarques/test/Shot/shot-consumer-compose/app/screenshots/pro/debug/com.karumi.shotconsumercompose.GreetingScreenshotTest_rendersAGreetingWithAnEmptyText.png
        at com.sksamuel.scrimage.Image$.fromPath(Image.scala:878)
        at com.sksamuel.scrimage.Image$.fromFile(Image.scala:875)
        at com.karumi.shot.screenshots.ScreenshotsSaver.getScreenshotDimension(ScreenshotsSaver.scala:73)
        at com.karumi.shot.Shot.$anonfun$readComposeScreenshotsMetadata$3(Shot.scala:267)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at scala.collection.TraversableLike.map(TraversableLike.scala:286)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
        at com.karumi.shot.Shot.readComposeScreenshotsMetadata(Shot.scala:265)
        at com.karumi.shot.Shot.recordComposeScreenshots(Shot.scala:172)
        at com.karumi.shot.Shot.recordScreenshots(Shot.scala:49)
        at com.karumi.shot.tasks.ExecuteScreenshotTests.executeScreenshotTests(Tasks.scala:88)
```

**Comment by pedrovgs** [comment]
I'm going to release a new version with the fix. 5.12.1 should fix it. Please, as soon as it is available, check if it is fixed and reopen this again if it is not.
