### ISSUE TITLE
Error: Fails to capture AlertDialog composable

### ISSUE THREAD

**Issue by prateek-kaushik** [pedrovgs/Shot#305]
The framework is throwing below error when I try to execute tests containing AlertDialog or Dialog composable.
Here is the stack trace:

```
java.lang.AssertionError: java.lang.AssertionError: Failed to capture a node to bitmap.
Reason: Expected exactly '1' node but found '2' nodes that satisfy: (isRoot)
Nodes found:
1) Node #1 at (l=0.0, t=160.0, r=0.0, b=160.0)px
2) Node #2 at (l=0.0, t=0.0, r=360.0, b=304.0)px
Has 1 child

at androidx.compose.ui.test.SemanticsNodeInteraction.fetchOneOrDie(SemanticsNodeInteraction.kt:172)
at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNode(SemanticsNodeInteraction.kt:106)
at androidx.compose.ui.test.AndroidImageHelpers_androidKt.captureToImage(AndroidImageHelpers.android.kt:40)
at com.karumi.shot.compose.SemanticsNodeBitmapGenerator.generateBitmap(SemanticsNodeBitmapGenerator.kt:12)
at com.karumi.shot.compose.ScreenshotSaver.getBitmapFromScreenshotToSave(ScreenshotSaver.kt:28)
at com.karumi.shot.compose.ScreenshotSaver.saveScreenshot(ScreenshotSaver.kt:19)
at com.karumi.shot.compose.ComposeScreenshot.saveScreenshot(ComposeScreenshot.kt:22)
at com.karumi.shot.ScreenshotTest$DefaultImpls.compareScreenshot(ScreenshotTest.kt:144)
...
```

Here is the sample AlertDialog composable in my test method:

```
AlertDialog(
                onDismissRequest = { },
                buttons = {
                    Button(onClick = { }) {
                        Text(text = "Button text")
                    }
                },
                title = {
                    Text(
                        text = "Title goes here"
                    )
                },
                text = {
                    Text(
                        text = "Message goes here"
                    )
                }
            )
```

**Comment by prateek-kaushik** [comment]
Further related code

I pass above mentioned AlertDialog or any composable to this below shot helper method
```
@get:Rule
    val composableRule = createComposeRule()
    
    fun shot(content: @Composable () -> Unit) {
        composableRule.setContent {
            CompositionLocalProvider(
                    LocalLayoutDirection provides if (isRTL) LayoutDirection.Rtl else LayoutDirection.Ltr
            ) {
                MyTheme(themeProvider = myThemeProvider, content = content)
            }
        }

        compareScreenshot(composableRule)
    }
```

**Comment by adrinieto** [comment]
We had the same problem with a custom Dialog. We made it work by capturing only the dialog, not the full screen.

First, add a test tag to the content of the dialog: `Modifier.testTag(YOUR_TAG)`
Then call `compareScreenshot()` using the tag node: 
```kotlin
compareScreenshot(composeRule.onNodeWithTag(YOUR_TAG, useUnmergedTree = true))
```

**Comment by prateek-kaushik** [comment]
Thanks @adrinieto for the solution. 
Coincidentally I had already implemented the same solution but forgot to update it here.
Ta.
